name       : python-babelfish
version    : 0.6.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/b/babelfish/babelfish-0.6.0.tar.gz : 2dadfadd1b205ca5fa5dc9fa637f5b7933160a0418684c7c46a7a664033208a2
license    : BSD-3-Clause
component  : programming.python
summary    : A module to work with countries and languages
description: |
    Babelfish makes it easy to work with countries, languages, scripts, ISO codes and IETF codes from Python. It has converters between all different data can be extended to use custom converters and data.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
