name       : python-babelfish
version    : 0.5.5
release    : 1
source     :
    - https://pypi.python.org/packages/34/b7/b36c651a9136990060ab4d6c9a32de81752123105b940b2f3b958e5c6cd0/babelfish-0.5.5.tar.gz : 8380879fa51164ac54a3e393f83c4551a275f03617f54a99d70151358e444104
license    : BSD-3-Clause
component  : programming.python
summary    : A module to work with countries and languages
description: |
    A module to work with countries and languages
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
