name       : python-babelfish
version    : 0.5.5
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/b/babelfish/babelfish-0.5.5.tar.gz : 8380879fa51164ac54a3e393f83c4551a275f03617f54a99d70151358e444104
license    : BSD-3-Clause
component  : programming.python
summary    : A module to work with countries and languages
description: |
    Babelfish makes it easy to work with countries, languages, scripts, ISO codes and IETF codes from Python. It has converters between all different data can be extended to use custom converters and data.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
